'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class view1

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''inpHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inpHide As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''isFormLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isFormLocked As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''XMLFileLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XMLFileLoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''mouseLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mouseLoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''div_position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_position As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''F8Pressed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F8Pressed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''F9Pressed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F9Pressed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblJavaScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJavaScript As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJavaScript2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJavaScript2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCHeader1 As Global.DOTForm1151.UCHeader

    '''<summary>
    '''pnlMainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMainPage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkNonSpecificPersonnel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNonSpecificPersonnel As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtRequestingAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestingAgency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''employeeFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employeeFullName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpBureau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpBureau As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBureau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBureau As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCapitol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCapitol As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optCapitol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optCapitol As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkCSOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCSOB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optCurtis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optCurtis As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkDSOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDSOB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optDocking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDocking As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkHarrisonCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHarrisonCenter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optESOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optESOB As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkLSOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLSOB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optLSOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optLSOB As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkMemorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMemorial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optMemorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optMemorial As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOther As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHCDataCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHCDataCenter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHCDataCenterSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHCDataCenterSO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHCHelpDesk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHCHelpDesk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optOther As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DSOBTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSOBTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UCSignatures1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCSignatures1 As Global.DOTForm1151.UCSignatures

    '''<summary>
    '''txtSupervisorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupervisorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CTRL103_6_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRL103_6_view1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtsuperSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsuperSignature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSuperPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuperPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bmName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bmName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CTRL104_6_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRL104_6_view1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtBMSig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMSig As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChiefSigs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChiefSigs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''bcsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bcsName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CTRL140_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTRL140_view1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bcsSig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bcsSig As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''employeeFullName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employeeFullName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCardnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardnumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlUCSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCSubmit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCSubmit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCSubmit1 As Global.DOTForm1151.UCSubmit

    '''<summary>
    '''pnlUCAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCAttachment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCAttachments1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCAttachments1 As Global.DOTForm1151.UCAttachments
End Class
